### ISSUE TITLE
Handling errors in projects.cfg

### ISSUE THREAD

**Issue by juhoinkinen** [NatLibFi/Annif#282]
Some syntax errors of  `projects.cfg` produce a lengthy generic Python error message, see e.g. https://groups.google.com/d/msg/annif-users/kIvJPbZ-vVU/zXDYFm6PAgAJ 

A more concise/specific error message would be better. Some errors are already handled, for example this exists: 
`"Error: Project 'maui-fi': vocab setting is missing"`

**Comment by juhoinkinen** [comment]
I accidentally had placed  `mauiservice.ini` in place of `projects.cfg`, which led to this error message:
```
root@lx8-9811-008:/annif_projects# annif list-projects
Project ID               Project Name                                 Language
------------------------------------------------------------------------------
kirjastonhoitaja         kirjastonhoitaja                             fi      
root@lx8-9811-008:/annif_projects# cat document.txt | annif suggest kirjastonhoitaja
Traceback (most recent call last):
  File "/usr/local/bin/annif", line 11, in <module>
    load_entry_point('annif', 'console_scripts', 'annif')()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 569, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 419, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Annif/annif/cli.py", line 165, in run_suggest
    hits = hit_filter(project.suggest(text, backend_params))
  File "/Annif/annif/project.py", line 175, in suggest
    hits = self._suggest_with_backend(text, backend_params)
  File "/Annif/annif/project.py", line 114, in _suggest_with_backend
    beparams = backend_params.get(self.backend.backend_id, {})
  File "/Annif/annif/project.py", line 130, in backend
    backend_id = self.config['backend']
  File "/usr/local/lib/python3.6/configparser.py", line 1233, in __getitem__
    raise KeyError(key)
KeyError: 'backend'
```

**Comment by osma** [comment]
Yes, this is a very good idea. Showing users a traceback is not very friendly.

This is also related to #273 which proposes that there should be default values for configuration settings. Many errors like this would be fixed by defaults, but obviously not all of them - for example a project without a `backend` setting cannot really work and it doesn't make sense to use a default backend in that case.
