### ISSUE TITLE
backend stwfsa training

### ISSUE THREAD

**Issue by buildvoc10** [NatLibFi/Annif#467]
running the annif train on the stwfsa get the following error
warning: Could not create backend stwfsa, make sure you've installed optional dependencies
Traceback (most recent call last):
  File "/usr/local/bin/annif", line 33, in <module>
    sys.exit(load_entry_point('annif', 'console_scripts', 'annif')())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Annif/annif/cli.py", line 205, in run_train
    proj.train(documents, backend_params)
  File "/Annif/annif/project.py", line 190, in train
    beparams = backend_params.get(self.backend.backend_id, {})
AttributeError: 'NoneType' object has no attribute 'backend_id'

**Comment by osma** [comment]
Please be more specific when you report problems. It's difficult to help without knowing the background.

I assume you're using the newly released Annif 0.51.

What's your operating system and Python version?

How did you install Annif (pip install, clone from GitHub, Docker..?)? Did you install from scratch or was it an upgrade from a previous version?

It looks like the dependencies needed for stwfsapy are not properly installed. If this is a development install (clone from github), and you've upgraded it using `git pull`, then you probably need to run `pip install -e .` or similar again to upgrade the dependencies.

Problems like this are better handled via the annif-users group, unless you're sure it's a bug.

**Comment by osma** [comment]
Closing due to inactivity, please reopen if necessary.
